### ISSUE TITLE
Which regressions to run to get equivalence result

### ISSUE THREAD

**Issue by arthurcbps** [borusyak/shift-share#2]
Hi Kirill,

I am planning to use the package to run SSIV regressions. I read the paper,  and if I understood correctly, the package provides a way to generate equivalent estimates considering shock-level and location-level regressions.

I didn't get this using my own data. To test whether I did something wrong, I ran two regressions using the ADH data provided in the replication package. Following as closely as possible what the help file says, I ran the following regressions:

At the location-level:

```
use location_level, clear
ivreg2 y (x = z) year t2 Lsh_manuf

``` 

Using the package to get a shock-level dataset:
```
ssaggregate y x z l_sh_routine33, n(sic87dd) t(year) s(ind_share) sfile(Lshares) l(czone) controls("t2 Lsh_manuf")
	replace sic87dd = 0 if missing(sic87dd)
	merge 1:1 sic87dd year using shocks, assert(1 3) nogen
	merge m:1 sic87dd using industries, assert(1 3) nogen
	
	foreach v of varlist g year sic3 {
      replace `v'= 0 if sic87dd == 0
          }
ivreg2 y (x=g) year [aw=s_n], r
```

If I understood correctly, the two regressions should have the same estimate for the coefficient on x. What I get instead are -.27 and -.19.

Did I understand the paper's result incorrectly or am I running the wrong regression?

Thanks a lot for the awesome package!

**Comment by borusyak** [comment]
Hi,
Our replication package provides correct uses of ssaggregate which imply the same coefficients at the regional and industry levels. It's a bit hard to guess what the issue is with your code but some possibilities are that (1) you don't include the addmissing option and (2) your industry regression includes the year dummy while the original regression doesn't include the corresponding regional control (the lagged total manufacturing share interacted with year). More broadly, you are not correcting for the incomplete shares problem, so you are running dangerous specifications which you should avoid.

Best,
Kirill

**Comment by arthurcbps** [comment]
thank you! Adding the addmissing option did the job
